# 0.&nbsp;Mount Google drive

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# 1.&nbsp;Libraries

In [ ]:
import os
import pandas as pd
import numpy as np

# 2.&nbsp;Data list

```
Folder PATH listing
Volume serial number is 567E-2928
C:.
    OneDrive_1_5-22-2023.zip
    tree.txt

No subfolders exist
```

```
Folder PATH listing
Volume serial number is 567E-2928
C:.
|   tree.txt
|
+---New_OTT (SuperMAG)
|   |   cleaned_OTT-2001-supermag.csv
|   |   cleaned_OTT-2001-supermaghc.csv
|   |   cleaned_OTT-2002-supermag.csv
|   |   cleaned_OTT-2002-supermaghc.csv
|   |   cleaned_OTT-2003-supermag.csv
|   |   cleaned_OTT-2003-supermaghc.csv
|   |   cleaned_OTT-2004-supermag.csv
|   |   cleaned_OTT-2004-supermaghc.csv
|   |   cleaned_OTT-2005-supermag.csv
|   |   cleaned_OTT-2005-supermaghc.csv
|   |   cleaned_OTT-2006-supermag.csv
|   |   cleaned_OTT-2006-supermaghc.csv
|   |   cleaned_OTT-2007-supermag.csv
|   |   cleaned_OTT-2007-supermaghc.csv
|   |   cleaned_OTT-2008-supermag.csv
|   |   cleaned_OTT-2008-supermaghc.csv
|   |   cleaned_OTT-2009-supermag.csv
|   |   cleaned_OTT-2009-supermaghc.csv
|   |   cleaned_OTT-2010-supermag.csv
|   |   cleaned_OTT-2010-supermaghc.csv
|   |   cleaned_OTT-2011-supermag.csv
|   |   cleaned_OTT-2011-supermaghc.csv
|   |   cleaned_OTT-2012-supermag.csv
|   |   cleaned_OTT-2012-supermaghc.csv
|   |   cleaned_OTT-2013-supermag.csv
|   |   cleaned_OTT-2013-supermaghc.csv
|   |   cleaned_OTT-2014-supermag.csv
|   |   cleaned_OTT-2014-supermaghc.csv
|   |   cleaned_OTT-2015-supermag.csv
|   |   cleaned_OTT-2015-supermaghc.csv
|   |   cleaned_OTT-2016-supermag.csv
|   |   cleaned_OTT-2016-supermaghc.csv
|   |   cleaned_OTT-2017-supermag.csv
|   |   cleaned_OTT-2017-supermaghc.csv
|   |   cleaned_OTT-2018-supermag.csv
|   |   cleaned_OTT-2018-supermaghc.csv
|   |   h_comp.m
|   |   README.boxnote
|   |
|   \---logs
|           OTT-2001-log.txt
|           OTT-2001-log_interpolation.csv
|           OTT-2002-log.txt
|           OTT-2002-log_interpolation.csv
|           OTT-2003-log.txt
|           OTT-2003-log_interpolation.csv
|           OTT-2004-log.txt
|           OTT-2004-log_interpolation.csv
|           OTT-2005-log.txt
|           OTT-2005-log_interpolation.csv
|           OTT-2006-log.txt
|           OTT-2006-log_interpolation.csv
|           OTT-2007-log.txt
|           OTT-2007-log_interpolation.csv
|           OTT-2008-log.txt
|           OTT-2008-log_interpolation.csv
|           OTT-2009-log.txt
|           OTT-2009-log_interpolation.csv
|           OTT-2010-log.txt
|           OTT-2010-log_interpolation.csv
|           OTT-2011-log.txt
|           OTT-2011-log_interpolation.csv
|           OTT-2012-log.txt
|           OTT-2012-log_interpolation.csv
|           OTT-2013-log.txt
|           OTT-2013-log_interpolation.csv
|           OTT-2014-log.txt
|           OTT-2014-log_interpolation.csv
|           OTT-2015-log.txt
|           OTT-2015-log_interpolation.csv
|           OTT-2016-log.txt
|           OTT-2016-log_interpolation.csv
|           OTT-2017-log.txt
|           OTT-2017-log_interpolation.csv
|           OTT-2018-log.txt
|           OTT-2018-log_interpolation.csv
|
\---Solar Wind (Omniweb)
        solar_analyze.m
        solar_wind_2001.lst
        solar_wind_2002.lst
        solar_wind_2003.lst
        solar_wind_2004.lst
        solar_wind_2005.lst
        solar_wind_2006.lst
        solar_wind_2007.lst
        solar_wind_2008.lst
        solar_wind_2009.lst
        solar_wind_2010.lst
        solar_wind_2011.lst
        solar_wind_2012.lst
        solar_wind_2013.lst
        solar_wind_2014.lst
        solar_wind_2015.lst
        solar_wind_2016.lst
        solar_wind_2017.lst
        solar_wind_2018.lst
```

# 3.&nbsp;Data acquisition

## 3.1. Solar Wind (Omniweb)

In [ ]:
path1 = "/content/drive/MyDrive/5. Research/1. Summer Project/2. Data/OneDrive_1_5-22-2023/Solar Wind (Omniweb)"

In [ ]:
filenames = os.listdir(path=path1)
filenames

In [ ]:
df1 = pd.read_csv(os.path.join(path1, filenames[0])) ; display("df1:", df1.shape, df1.head(1))

## 3.2. SuperMAG

In [ ]:
path2 = "/content/drive/MyDrive/5. Research/1. Summer Project/2. Data/OneDrive_1_5-22-2023/New_OTT (SuperMAG)"

In [ ]:
filenames = os.listdir(path=path2)
filenames

['logs',
 'cleaned_OTT-2001-supermaghc.csv',
 'cleaned_OTT-2002-supermag.csv',
 'cleaned_OTT-2001-supermag.csv',
 'cleaned_OTT-2005-supermaghc.csv',
 'cleaned_OTT-2003-supermag.csv',
 'cleaned_OTT-2003-supermaghc.csv',
 'cleaned_OTT-2004-supermaghc.csv',
 'cleaned_OTT-2005-supermag.csv',
 'cleaned_OTT-2004-supermag.csv',
 'cleaned_OTT-2002-supermaghc.csv',
 'cleaned_OTT-2006-supermag.csv',
 'cleaned_OTT-2007-supermag.csv',
 'cleaned_OTT-2008-supermaghc.csv',
 'cleaned_OTT-2007-supermaghc.csv',
 'cleaned_OTT-2009-supermag.csv',
 'cleaned_OTT-2006-supermaghc.csv',
 'cleaned_OTT-2008-supermag.csv',
 'cleaned_OTT-2010-supermaghc.csv',
 'cleaned_OTT-2010-supermag.csv',
 'cleaned_OTT-2012-supermaghc.csv',
 'cleaned_OTT-2011-supermaghc.csv',
 'cleaned_OTT-2011-supermag.csv',
 'cleaned_OTT-2012-supermag.csv',
 'cleaned_OTT-2009-supermaghc.csv',
 'cleaned_OTT-2016-supermag.csv',
 'cleaned_OTT-2014-supermaghc.csv',
 'cleaned_OTT-2014-supermag.csv',
 'cleaned_OTT-2013-supermaghc.csv',
 'cleaned_OTT-2015-supermag.csv',
 'cleaned_OTT-2013-supermag.csv',
 'cleaned_OTT-2015-supermaghc.csv',
 'cleaned_OTT-2017-supermaghc.csv',
 'h_comp.m',
 'cleaned_OTT-2016-supermaghc.csv',
 'cleaned_OTT-2017-supermag.csv',
 'cleaned_OTT-2018-supermaghc.csv',
 'README.boxnote',
 'cleaned_OTT-2018-supermag.csv']

In [ ]:
df2 = pd.read_csv(os.path.join(path2, filenames[2])) ; display("df2:", df2.shape, df2.head(1))

'df2:'

(525600, 14)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE
0,2002,1,1,0,0,OTT,18.92,55.79,-14.29,115.52,-11.4,-2.8,17.5,21.072494

In [ ]:
filenames[2]

'cleaned_OTT-2002-supermag.csv'

# 4.&nbsp;Data exploration

## 4.1. SuperMAG

In [ ]:
path_SuperMAG = "/content/drive/MyDrive/5. Research/1. Summer Project/2. Data/OneDrive_1_5-22-2023/New_OTT (SuperMAG)"

In [ ]:
files = os.listdir(path_SuperMAG)
files_csv = [item for item in files if item[-4:].lower()==".csv"]
files_csv.sort()
files_y = [item for item in files_csv if item[-6:].lower()=="hc.csv"]
files_x = [item for item in files_csv if item[-6:].lower()!="hc.csv"]
files_y

['cleaned_OTT-2001-supermaghc.csv',
 'cleaned_OTT-2002-supermaghc.csv',
 'cleaned_OTT-2003-supermaghc.csv',
 'cleaned_OTT-2004-supermaghc.csv',
 'cleaned_OTT-2005-supermaghc.csv',
 'cleaned_OTT-2006-supermaghc.csv',
 'cleaned_OTT-2007-supermaghc.csv',
 'cleaned_OTT-2008-supermaghc.csv',
 'cleaned_OTT-2009-supermaghc.csv',
 'cleaned_OTT-2010-supermaghc.csv',
 'cleaned_OTT-2011-supermaghc.csv',
 'cleaned_OTT-2012-supermaghc.csv',
 'cleaned_OTT-2013-supermaghc.csv',
 'cleaned_OTT-2014-supermaghc.csv',
 'cleaned_OTT-2015-supermaghc.csv',
 'cleaned_OTT-2016-supermaghc.csv',
 'cleaned_OTT-2017-supermaghc.csv',
 'cleaned_OTT-2018-supermaghc.csv']

In [ ]:
dfx = pd.read_csv(os.path.join(path_SuperMAG, files_x[0])) ; display("dfx:", dfx.shape, dfx.head(1)) ; print()
dfx.isna().sum()

'dfx:'

(525600, 14)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE
0,2001,1,1,0,0,OTT,18.92,55.86,-14.33,115.48,3.1,1.3,2.8,4.374929

YEAR           0
MONTH          0
DAY            0
HOUR           0
MINUTE         0
IAGA           0
MLT          622
MLAT         622
IGRF_DECL    622
SZA          622
N            622
E            622
Z            622
MAGNITUDE    622
dtype: int64

In [ ]:
dfy = pd.read_csv(os.path.join(path_SuperMAG, files_y[0]), header=None) ; display("dfy:", dfy.shape, dfy.head(1)) ; print()
dfy.columns = ["y"]
dfy.isna().sum()

'dfy:'

(525600, 1)

          0
0  3.361547

y    622
dtype: int64

In [ ]:
dfxy = pd.concat([dfx, dfy], axis=1) ; display("dfxy:", dfxy.shape, dfxy.head(1)) ; print()

'dfxy:'

(525600, 15)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
0,2001,1,1,0,0,OTT,18.92,55.86,-14.33,115.48,3.1,1.3,2.8,4.374929,3.361547

In [ ]:
for itemx, itemy in zip(files_x, files_y):
    dfx = pd.read_csv(os.path.join(path_SuperMAG, itemx))
    dfy = pd.read_csv(os.path.join(path_SuperMAG, itemy), header=None)
    dfy.columns = ["y"]
    dfxy = pd.concat([dfx, dfy], axis=1) ; display("dfxy:", dfxy.shape, dfxy.head(1)) ; print()
    display(dfxy.isna().sum()) ; print()

'dfxy:'

(525600, 15)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
0,2001,1,1,0,0,OTT,18.92,55.86,-14.33,115.48,3.1,1.3,2.8,4.374929,3.361547

YEAR           0
MONTH          0
DAY            0
HOUR           0
MINUTE         0
IAGA           0
MLT          622
MLAT         622
IGRF_DECL    622
SZA          622
N            622
E            622
Z            622
MAGNITUDE    622
y            622
dtype: int64

'dfxy:'

(525600, 15)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
0,2002,1,1,0,0,OTT,18.92,55.79,-14.29,115.52,-11.4,-2.8,17.5,21.072494,11.738824

YEAR            0
MONTH           0
DAY             0
HOUR            0
MINUTE          0
IAGA            0
MLT          1459
MLAT         1459
IGRF_DECL    1459
SZA          1459
N            1459
E            1459
Z            1459
MAGNITUDE    1459
y            1459
dtype: int64

'dfxy:'

(525600, 15)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
0,2003,1,1,0,0,OTT,18.93,55.72,-14.25,115.55,-2.5,-5.4,2.2,6.344289,5.95063

YEAR          0
MONTH         0
DAY           0
HOUR          0
MINUTE        0
IAGA          0
MLT          96
MLAT         96
IGRF_DECL    96
SZA          96
N            96
E            96
Z            96
MAGNITUDE    96
y            96
dtype: int64

'dfxy:'

(527040, 15)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
0,2004,1,1,0,0,OTT,18.93,55.65,-14.2,115.58,-3.9,6.5,13.5,15.482571,7.580237

YEAR           0
MONTH          0
DAY            0
HOUR           0
MINUTE         0
IAGA           0
MLT          308
MLAT         308
IGRF_DECL    308
SZA          308
N            308
E            308
Z            308
MAGNITUDE    308
y            308
dtype: int64

'dfxy:'

(525600, 15)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
0,2005,1,1,0,0,OTT,18.93,55.58,-14.16,115.48,0.0,3.9,1.4,4.14367,3.9

YEAR            0
MONTH           0
DAY             0
HOUR            0
MINUTE          0
IAGA            0
MLT          1754
MLAT         1754
IGRF_DECL    1754
SZA          1754
N            1754
E            1754
Z            1754
MAGNITUDE    1754
y            1754
dtype: int64

'dfxy:'

(525600, 15)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
0,2006,1,1,0,0,OTT,18.93,55.46,-14.11,115.52,-11.9,-6.4,16.3,21.172152,13.511847

YEAR            0
MONTH           0
DAY             0
HOUR            0
MINUTE          0
IAGA            0
MLT          2380
MLAT         2380
IGRF_DECL    2380
SZA          2380
N            2380
E            2380
Z            2380
MAGNITUDE    2380
y            2380
dtype: int64

'dfxy:'

(525600, 15)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
0,2007,1,1,0,0,OTT,18.93,55.34,-14.06,115.55,6.6,4.2,-0.4,7.833262,7.823043

YEAR            0
MONTH           0
DAY             0
HOUR            0
MINUTE          0
IAGA            0
MLT          4640
MLAT         4640
IGRF_DECL    4640
SZA          4640
N            4640
E            4640
Z            4640
MAGNITUDE    4640
y            4640
dtype: int64

'dfxy:'

(527040, 15)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
0,2008,1,1,0,0,OTT,18.94,55.22,-14.02,115.58,-3.3,-0.7,3.0,4.514421,3.373426

YEAR             0
MONTH            0
DAY              0
HOUR             0
MINUTE           0
IAGA             0
MLT          13263
MLAT         13263
IGRF_DECL    13263
SZA          13263
N            13263
E            13263
Z            13263
MAGNITUDE    13263
y            13263
dtype: int64

'dfxy:'

(525600, 15)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
0,2009,1,1,0,0,OTT,18.94,55.1,-13.97,115.48,-8.8,10.6,2.0,13.921207,13.776792

YEAR            0
MONTH           0
DAY             0
HOUR            0
MINUTE          0
IAGA            0
MLT          3953
MLAT         3953
IGRF_DECL    3953
SZA          3953
N            3953
E            3953
Z            3953
MAGNITUDE    3953
y            3953
dtype: int64

'dfxy:'

(525600, 15)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
0,2010,1,1,0,0,OTT,18.94,54.98,-13.92,115.51,-2.5,0.1,2.4,3.466987,2.501999

YEAR            0
MONTH           0
DAY             0
HOUR            0
MINUTE          0
IAGA            0
MLT          1184
MLAT         1184
IGRF_DECL    1184
SZA          1184
N            1184
E            1184
Z            1184
MAGNITUDE    1184
y            1184
dtype: int64

'dfxy:'

(525600, 15)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
0,2011,1,1,0,0,OTT,18.94,54.98,-13.86,115.54,-7.7,-0.6,4.8,9.093404,7.723341

YEAR            0
MONTH           0
DAY             0
HOUR            0
MINUTE          0
IAGA            0
MLT          1051
MLAT         1051
IGRF_DECL    1051
SZA          1051
N            1051
E            1051
Z            1051
MAGNITUDE    1051
y            1051
dtype: int64

'dfxy:'

(527040, 15)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
0,2012,1,1,0,0,OTT,18.94,54.98,-13.81,115.58,-4.1,-0.1,3.6,5.457105,4.101219

YEAR             0
MONTH            0
DAY              0
HOUR             0
MINUTE           0
IAGA             0
MLT          14561
MLAT         14561
IGRF_DECL    14561
SZA          14561
N            14561
E            14561
Z            14561
MAGNITUDE    14561
y            14561
dtype: int64

'dfxy:'

(525600, 15)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
0,2013,1,1,0,0,OTT,18.94,54.98,-13.75,115.47,-1.1,1.2,1.7,2.35372,1.627882

YEAR          0
MONTH         0
DAY           0
HOUR          0
MINUTE        0
IAGA          0
MLT          48
MLAT         48
IGRF_DECL    48
SZA          48
N            48
E            48
Z            48
MAGNITUDE    48
y            48
dtype: int64

'dfxy:'

(525600, 15)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
0,2014,1,1,0,0,OTT,18.94,54.98,-13.69,115.51,2.4,-1.4,-1.4,3.11127,2.778489

YEAR            0
MONTH           0
DAY             0
HOUR            0
MINUTE          0
IAGA            0
MLT          2486
MLAT         2486
IGRF_DECL    2486
SZA          2486
N            2486
E            2486
Z            2486
MAGNITUDE    2486
y            2486
dtype: int64

'dfxy:'

(525600, 15)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
0,2015,1,1,0,0,OTT,18.94,54.98,-13.64,115.54,-4.0,0.7,3.1,5.108816,4.060788

YEAR            0
MONTH           0
DAY             0
HOUR            0
MINUTE          0
IAGA            0
MLT          4874
MLAT         4874
IGRF_DECL    4874
SZA          4874
N            4874
E            4874
Z            4874
MAGNITUDE    4874
y            4874
dtype: int64

'dfxy:'

(527040, 15)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
0,2016,1,1,0,0,OTT,18.94,54.98,-13.59,115.57,-79.2,68.6,75.2,128.97147,104.778815

YEAR            0
MONTH           0
DAY             0
HOUR            0
MINUTE          0
IAGA            0
MLT          1313
MLAT         1313
IGRF_DECL    1313
SZA          1313
N            1313
E            1313
Z            1313
MAGNITUDE    1313
y            1313
dtype: int64

'dfxy:'

(525600, 15)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
0,2017,1,1,0,0,OTT,18.94,54.98,-13.53,115.47,-5.7,0.1,8.1,9.905049,5.700877

YEAR          0
MONTH         0
DAY           0
HOUR          0
MINUTE        0
IAGA          0
MLT          89
MLAT         89
IGRF_DECL    89
SZA          89
N            89
E            89
Z            89
MAGNITUDE    89
y            89
dtype: int64

'dfxy:'

(525600, 15)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
0,2018,1,1,0,0,OTT,18.94,54.98,-13.48,115.51,-12.5,-15.7,7.4,21.38925,20.068383

YEAR           0
MONTH          0
DAY            0
HOUR           0
MINUTE         0
IAGA           0
MLT          614
MLAT         614
IGRF_DECL    614
SZA          614
N            614
E            614
Z            614
MAGNITUDE    614
y            614
dtype: int64

- many nones
- 525600 =
Common year (365 days):
There are 24 hours in a day and 60 minutes in an hour. So, to find the number of minutes in a day: 24 hours x 60 minutes = 1,440 minutes.
Now, multiply the number of minutes in a day by the number of days in a common year: 1,440 minutes x 365 days = 525,600 minutes.

In [ ]:
list0 = []
for itemx, itemy in zip(files_x, files_y):
    dfx = pd.read_csv(os.path.join(path_SuperMAG, itemx))
    dfy = pd.read_csv(os.path.join(path_SuperMAG, itemy), header=None)
    dfy.columns = ["y"]
    dfxy = pd.concat([dfx, dfy], axis=1) #; display("dfxy:", dfxy.shape, dfxy.head(1)) ; print()
    #display(dfxy.isna().sum()) ; print()
    list0.append(dfxy)

df_SuperMAG = pd.concat(list0) ; display("df_SuperMAG:", df_SuperMAG.shape, df_SuperMAG.head(1)) ; print()

'df_SuperMAG:'

(9466560, 15)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
0,2001,1,1,0,0,OTT,18.92,55.86,-14.33,115.48,3.1,1.3,2.8,4.374929,3.361547

In [ ]:
df_SuperMAG.loc[df_SuperMAG.y.isna(), :].notna().sum()

YEAR         54695
MONTH        54695
DAY          54695
HOUR         54695
MINUTE       54695
IAGA         54695
MLT              0
MLAT             0
IGRF_DECL        0
SZA              0
N                0
E                0
Z                0
MAGNITUDE        0
y                0
dtype: int64

In [ ]:
df_SuperMAG.dtypes

YEAR           int64
MONTH          int64
DAY            int64
HOUR           int64
MINUTE         int64
IAGA          object
MLT          float64
MLAT         float64
IGRF_DECL    float64
SZA          float64
N            float64
E            float64
Z            float64
MAGNITUDE    float64
y            float64
dtype: object

In [ ]:
df_SuperMAG.memory_usage()/1024/1024

Index        72.224121
YEAR         72.224121
MONTH        72.224121
DAY          72.224121
HOUR         72.224121
MINUTE       72.224121
IAGA         72.224121
MLT          72.224121
MLAT         72.224121
IGRF_DECL    72.224121
SZA          72.224121
N            72.224121
E            72.224121
Z            72.224121
MAGNITUDE    72.224121
y            72.224121
dtype: float64

In [ ]:
df_SuperMAG.IAGA.value_counts()

OTT    9466560
Name: IAGA, dtype: int64

- IAGA: categorical or drop
- date time: year, month, day, hour, minute

In [ ]:
df_SuperMAG.loc[:, "date_time"] = pd.to_datetime(df_SuperMAG.loc[:, ["YEAR", "MONTH", "DAY", "HOUR", "MINUTE"]]) ; display("df_SuperMAG:", df_SuperMAG.shape, df_SuperMAG.head(2)) ; print()

<ipython-input-58-cec61a0f159c>:1: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_SuperMAG.loc[:, "date_time"] = pd.to_datetime(df_SuperMAG.loc[:, ["YEAR", "MONTH", "DAY", "HOUR", "MINUTE"]]) ; display("df_SuperMAG:", df_SuperMAG.shape, df_SuperMAG.head(2)) ; print()

'df_SuperMAG:'

(9466560, 16)

,YEAR,MONTH,DAY,HOUR,MINUTE,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y,date_time
0,2001,1,1,0,0,OTT,18.92,55.86,-14.33,115.48,3.1,1.3,2.8,4.374929,3.361547,2001-01-01 00:00:00
1,2001,1,1,0,1,OTT,18.94,55.86,-14.33,115.66,2.4,0.1,2.8,3.689173,2.402082,2001-01-01 00:01:00

- day time: head 2

In [ ]:
df_SuperMAG = df_SuperMAG.loc[:, ["date_time", "IAGA", "MLT", "MLAT", "IGRF_DECL", "SZA", "N", "E", "Z", "MAGNITUDE", "y"]] ; display("df_SuperMAG:", df_SuperMAG.shape, df_SuperMAG.head(2)) ; print()

'df_SuperMAG:'

(9466560, 11)

,date_time,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
0,2001-01-01 00:00:00,OTT,18.92,55.86,-14.33,115.48,3.1,1.3,2.8,4.374929,3.361547
1,2001-01-01 00:01:00,OTT,18.94,55.86,-14.33,115.66,2.4,0.1,2.8,3.689173,2.402082

In [ ]:
df_SuperMAG.memory_usage()/1024/1024

Index        72.224121
date_time    72.224121
IAGA         72.224121
MLT          72.224121
MLAT         72.224121
IGRF_DECL    72.224121
SZA          72.224121
N            72.224121
E            72.224121
Z            72.224121
MAGNITUDE    72.224121
y            72.224121
dtype: float64

In [ ]:
df_SuperMAG.to_parquet("SuperMAG.parq", index=False)

In [ ]:
df_SuperMAG.loc[df_SuperMAG.y.isna(), :].head(20)

,date_time,IAGA,MLT,MLAT,IGRF_DECL,SZA,N,E,Z,MAGNITUDE,y
49239,2001-02-04 04:39:00,OTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49240,2001-02-04 04:40:00,OTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49241,2001-02-04 04:41:00,OTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49242,2001-02-04 04:42:00,OTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49243,2001-02-04 04:43:00,OTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49244,2001-02-04 04:44:00,OTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49245,2001-02-04 04:45:00,OTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49246,2001-02-04 04:46:00,OTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49247,2001-02-04 04:47:00,OTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49248,2001-02-04 04:48:00,OTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49249,2001-02-04 04:49:00,OTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49250,2001-02-04 04:50:00,OTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49251,2001-02-04 04:51:00,OTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49252,2001-02-04 04:52:00,OTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49253,2001-02-04 04:53:00,OTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49254,2001-02-04 04:54:00,OTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49255,2001-02-04 04:55:00,OTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49256,2001-02-04 04:56:00,OTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49257,2001-02-04 04:57:00,OTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49258,2001-02-04 04:58:00,OTT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN